---
version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: smartbrain
    ports:
      - 5432:5432
    volumes:
      - smartbrain-db-data:/var/lib/postgresql/data
      - $PWD/db/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
volumes:
  smartbrain-db-data:
